# CommandHelp Fish Hook — generated by `chelp init fish`.
#
# Ctrl+Space : natural-language query, modal, result lands on the prompt
# Tab / Right : accept the completion (falls back to the stock widget)

# Warm the daemon so the first completion is served inside the 15ms budget.
# Privacy kill switch: CHELP_DISABLE_DAEMON=1 degrades to a no-op hook.
if test "$CHELP_DISABLE_DAEMON" = "1"
    exit 0
end
command chelp daemon --detached >/dev/null 2>&1

function __chelp_query
    set -l tmp "/tmp/chelp-query-$fish_pid"
    command touch $tmp 2>/dev/null
    command chelp query (commandline -b) --out-file $tmp 2>/dev/null
    set -l lines (command cat $tmp 2>/dev/null)
    command rm -f $tmp
    # File holds `run|edit` on line 1 and the command on the rest; empty on cancel.
    test (count $lines) -ge 2; or return
    set -l action $lines[1]
    set -l cmd (string join \n $lines[2..-1])
    test -n "$cmd"; or return
    commandline -r -- $cmd
    if test "$action" = run
        commandline -f execute
    else
        commandline -f repaint
    end
end

function __chelp_accept
    set -l buf (commandline -b)
    test -n "$buf"; or return
    set -l line (command chelp complete -- $buf 2>/dev/null | head -n 1)
    if test -n "$line"; and string match -q -- "$buf*" $line; and test (string length -- "$line") -gt (string length -- "$buf")
        commandline -r -- $line
    else if test "$argv[1]" = tab
        commandline -f complete
    else
        commandline -f forward-char
    end
end

bind \C-space __chelp_query
bind \t __chelp_accept tab
bind -k right __chelp_accept forward
bind \e\[C __chelp_accept forward
