# CommandHelp Zsh Hook — generated by `chelp init zsh`.
#
# Ctrl+Space    : natural-language query, modal, result lands on the prompt
# Tab / Right   : accept the ghost-text suggestion (falls back to the stock widget)

# Warm the daemon so the first completion is served inside the 15ms budget.
# Privacy kill switch: CHELP_DISABLE_DAEMON=1 degrades to a no-op hook (no spawn,
# no completion calls) for audited/HIPAA workstations.
if [[ "${CHELP_DISABLE_DAEMON:-}" != "1" ]]; then
  command chelp daemon --detached >/dev/null 2>&1
else
  return 0
fi

# --- Trigger 2: natural language ------------------------------------------
_chelp_query() {
  local tmp out action cmd
  tmp="${TMPDIR:-/tmp}/chelp-query-$$"
  : > "$tmp"
  command chelp query "$BUFFER" --out-file "$tmp" 2>/dev/null
  out="$(<"$tmp")"
  command rm -f "$tmp"
  # File holds `run|edit` on line 1 and the command on the rest; empty on cancel.
  [[ "$out" == *$'\n'* ]] || { zle redisplay; return 0 }
  action="${out%%$'\n'*}"
  cmd="${out#*$'\n'}"
  cmd="${cmd//$'\r'/}"
  [[ -n "$cmd" ]] || { zle redisplay; return 0 }
  BUFFER="$cmd"
  CURSOR=${#BUFFER}
  if [[ "$action" == run ]]; then
    zle accept-line
  else
    zle redisplay
  fi
}

# --- Trigger 1: ghost text -------------------------------------------------
_chelp_ghost() {
  POSTDISPLAY=''
  [[ -n "$BUFFER" ]] || return 0
  local line
  line="$(command chelp complete -- "$BUFFER" 2>/dev/null | command head -n 1)"
  if [[ -n "$line" && "$line" == "$BUFFER"* && ${#line} -gt ${#BUFFER} ]]; then
    POSTDISPLAY="${line#$BUFFER}"
  fi
  return 0
}

_chelp_accept_or() {
  if [[ -n "$POSTDISPLAY" ]]; then
    BUFFER="$BUFFER$POSTDISPLAY"
    CURSOR=${#BUFFER}
    POSTDISPLAY=''
  else
    zle "$1"
  fi
  return 0
}

_chelp_tab()   { _chelp_accept_or expand-or-complete }
_chelp_right() { _chelp_accept_or forward-char }

zle -N chelp-query _chelp_query
zle -N chelp-tab   _chelp_tab
zle -N chelp-right _chelp_right

autoload -Uz add-zle-hook-widget 2>/dev/null
add-zle-hook-widget line-pre-redraw _chelp_ghost 2>/dev/null

bindkey '^ '   chelp-query
bindkey '^I'   chelp-tab
bindkey '^[[C' chelp-right
bindkey '^OC'  chelp-right
