# CommandHelp Bash Hook — generated by `chelp init bash`.
#
# Ctrl+Space : natural-language query, modal, result lands on the prompt
# Right      : accept the completion (falls back to moving the cursor one cell)
#
# Tab is deliberately left to readline: hijacking it would delete filename
# completion, which is a worse loss than gaining suggestion acceptance.

# bash 3.2 (the /bin/bash shipped with macOS) runs `bind -x` handlers but does
# not let them read or write READLINE_LINE, so nothing here could work: stay out
# of the way instead of half-working.
if [ "${BASH_VERSINFO[0]}" -ge 4 ]; then

# Warm the daemon so the first completion is served inside the 15ms budget.
chelp daemon --detached >/dev/null 2>&1

_chelp_query() {
  local tmp out action cmd
  tmp="${TMPDIR:-/tmp}/chelp-query-$$"
  : > "$tmp"
  chelp query "$READLINE_LINE" --out-file "$tmp" 2>/dev/null
  out="$(cat "$tmp" 2>/dev/null)"
  rm -f "$tmp"
  # File holds `run|edit` on line 1 and the command on the rest; empty on cancel.
  case "$out" in
    *$'\n'*) ;;
    *) return 0 ;;
  esac
  action="${out%%$'\n'*}"
  cmd="${out#*$'\n'}"
  cmd="${cmd//$'\r'/}"
  [ -n "$cmd" ] || return 0
  if [ "$action" = run ]; then
    history -s "$cmd"
    READLINE_LINE=""
    READLINE_POINT=0
    eval "$cmd"
  else
    READLINE_LINE="$cmd"
    READLINE_POINT=${#READLINE_LINE}
  fi
}

_chelp_forward() {
  local suggestion
  if [ -n "$READLINE_LINE" ]; then
    suggestion="$(chelp complete -- "$READLINE_LINE" 2>/dev/null | head -n 1)"
    if [ -n "$suggestion" ] && [ "${suggestion#"$READLINE_LINE"}" != "$suggestion" ] \
        && [ "${#suggestion}" -gt "${#READLINE_LINE}" ]; then
      READLINE_LINE="$suggestion"
      READLINE_POINT=${#READLINE_LINE}
      return 0
    fi
  fi
  # No suggestion: behave like forward-char (readline's Right arrow).
  if [ "$READLINE_POINT" -lt "${#READLINE_LINE}" ]; then
    READLINE_POINT=$((READLINE_POINT + 1))
  fi
  return 0
}

# Escape sequences cannot be bound with `bind -x` on every bash build (older
# ones report "cannot find keymap for command"), so Right arrow is mapped to a
# control key through a macro, and the control key carries the handler.
bind -x '"\C-g": _chelp_forward'
bind '"\e[C": "\C-g"'
bind '"\eOC": "\C-g"'
bind -x '"\C-@": _chelp_query'

fi
