# CommandHelp PowerShell Hook — generated by `chelp init pwsh`.
#
# Ctrl+Space : natural-language query, modal, result lands on the prompt
# Tab / Right: accept the completion (falls back to the stock behaviour)

# Warm the daemon so the first completion is served inside the 15ms budget.
# Privacy kill switch: CHELP_DISABLE_DAEMON=1 degrades to a no-op hook (no spawn,
# no completion calls) for audited/HIPAA workstations.
if ($env:CHELP_DISABLE_DAEMON -eq "1") { return }
chelp daemon --detached 2>$null

function Read-ChelpResult {
    param([string]$Path)
    if (-not (Test-Path -LiteralPath $Path)) { return $null }
    $raw = Get-Content -LiteralPath $Path -Raw -ErrorAction SilentlyContinue
    if (-not $raw) { return $null }
    $idx = $raw.IndexOf("`n")
    if ($idx -lt 0) { return $null }
    $action = $raw.Substring(0, $idx).Trim()
    $command = $raw.Substring($idx + 1).TrimEnd()
    if ([string]::IsNullOrWhiteSpace($command)) { return $null }
    return [pscustomobject]@{ Action = $action; Command = $command }
}

function Get-ChelpSuggestion {
    param([string]$Buffer)
    if ([string]::IsNullOrWhiteSpace($Buffer)) { return $null }
    $first = chelp complete -- $Buffer 2>$null | Select-Object -First 1
    if (-not $first) { return $null }
    $line = "$first"
    if ($line.Length -gt $Buffer.Length -and $line.StartsWith($Buffer)) { return $line }
    return $null
}

# Unbind conflicting default MenuComplete if present, then bind chelp query
$chelpQueryBlock = {
    $line = $null
    $cursor = $null
    [Microsoft.PowerShell.PSConsoleReadLine]::GetBufferState([ref]$line, [ref]$cursor)

    $tmp = [System.IO.Path]::GetTempFileName()
    # The modal draws on the terminal; only the result is written to the file.
    chelp query "$line" --out-file $tmp 2>$null
    $result = Read-ChelpResult $tmp
    Remove-Item -LiteralPath $tmp -ErrorAction SilentlyContinue

    if ($result) {
        [Microsoft.PowerShell.PSConsoleReadLine]::RevertLine()
        [Microsoft.PowerShell.PSConsoleReadLine]::Insert($result.Command)
        if ($result.Action -eq 'run') {
            [Microsoft.PowerShell.PSConsoleReadLine]::AcceptLine()
        }
    }
}

try {
    Set-PSReadLineKeyHandler -Chord 'Ctrl+Space' -ScriptBlock $chelpQueryBlock -ErrorAction SilentlyContinue
} catch {}
Set-PSReadLineKeyHandler -Chord 'Ctrl+ ' -ScriptBlock $chelpQueryBlock

Set-PSReadLineKeyHandler -Key RightArrow -ScriptBlock {
    $line = $null
    $cursor = $null
    [Microsoft.PowerShell.PSConsoleReadLine]::GetBufferState([ref]$line, [ref]$cursor)
    if ($cursor -eq $line.Length -and $line.Length -gt 0) {
        $suggestion = Get-ChelpSuggestion $line
        if ($suggestion) {
            [Microsoft.PowerShell.PSConsoleReadLine]::RevertLine()
            [Microsoft.PowerShell.PSConsoleReadLine]::Insert($suggestion)
            return
        }
    }
    [Microsoft.PowerShell.PSConsoleReadLine]::ForwardChar()
}

Set-PSReadLineKeyHandler -Key Tab -ScriptBlock {
    $line = $null
    $cursor = $null
    [Microsoft.PowerShell.PSConsoleReadLine]::GetBufferState([ref]$line, [ref]$cursor)
    $suggestion = Get-ChelpSuggestion $line
    if ($suggestion) {
        [Microsoft.PowerShell.PSConsoleReadLine]::RevertLine()
        [Microsoft.PowerShell.PSConsoleReadLine]::Insert($suggestion)
        return
    }
    [Microsoft.PowerShell.PSConsoleReadLine]::TabCompleteNext()
}
